In [6]:
print("Matrix")
M=np.array([[ 7,  8,  9, 10],
 [11, 12, 13, 14],
 [15, 16, 17, 18]])
print("matrix:",M)
print(M.size)
print(M.shape)
print("Transpose")
transpose_mat=M.T
print("Traspose:",transpose_mat)
print("size:",transpose_mat.size)
print("shape:",transpose_mat.shape)


Matrix
matrix: [[ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
12
(3, 4)
Transpose
Traspose: [[ 7 11 15]
 [ 8 12 16]
 [ 9 13 17]
 [10 14 18]]
size: 12
shape: (4, 3)


In [7]:
import numpy as np

In [3]:
array_A = np.array([5, 10, 15, 20, 25])
array_B = np.array([2, 4, 6, 8, 10])
print("array_A:", array_A)
print("array_B:", array_B)

# 2. Add & Print
sum_array = array_A + array_B
print("sum_array:", sum_array)

array_A: [ 5 10 15 20 25]
array_B: [ 2  4  6  8 10]
sum_array: [ 7 14 21 28 35]
